/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChildComponent {
        "childMessage": string;
    }
    interface ComponentWithEvent {
        "message": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        "initialCount": number;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ParentComponent {
        "childMessage": string;
        "parentMessage": string;
    }
    interface StencilKitButton {
        "buttonTitle": string;
    }
    interface StencilKitDiv {
    }
    interface StencilKitLink {
        "href": string;
        "linkTitle": string;
    }
}
declare global {
    interface HTMLChildComponentElement extends Components.ChildComponent, HTMLStencilElement {
    }
    var HTMLChildComponentElement: {
        prototype: HTMLChildComponentElement;
        new (): HTMLChildComponentElement;
    };
    interface HTMLComponentWithEventElement extends Components.ComponentWithEvent, HTMLStencilElement {
    }
    var HTMLComponentWithEventElement: {
        prototype: HTMLComponentWithEventElement;
        new (): HTMLComponentWithEventElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {
    }
    var HTMLParentComponentElement: {
        prototype: HTMLParentComponentElement;
        new (): HTMLParentComponentElement;
    };
    interface HTMLStencilKitButtonElement extends Components.StencilKitButton, HTMLStencilElement {
    }
    var HTMLStencilKitButtonElement: {
        prototype: HTMLStencilKitButtonElement;
        new (): HTMLStencilKitButtonElement;
    };
    interface HTMLStencilKitDivElement extends Components.StencilKitDiv, HTMLStencilElement {
    }
    var HTMLStencilKitDivElement: {
        prototype: HTMLStencilKitDivElement;
        new (): HTMLStencilKitDivElement;
    };
    interface HTMLStencilKitLinkElement extends Components.StencilKitLink, HTMLStencilElement {
    }
    var HTMLStencilKitLinkElement: {
        prototype: HTMLStencilKitLinkElement;
        new (): HTMLStencilKitLinkElement;
    };
    interface HTMLElementTagNameMap {
        "child-component": HTMLChildComponentElement;
        "component-with-event": HTMLComponentWithEventElement;
        "my-component": HTMLMyComponentElement;
        "parent-component": HTMLParentComponentElement;
        "stencil-kit-button": HTMLStencilKitButtonElement;
        "stencil-kit-div": HTMLStencilKitDivElement;
        "stencil-kit-link": HTMLStencilKitLinkElement;
    }
}
declare namespace LocalJSX {
    interface ChildComponent {
        "childMessage"?: string;
    }
    interface ComponentWithEvent {
        "message"?: string;
        "onNew-message"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        "initialCount"?: number;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParentComponent {
        "childMessage"?: string;
        "parentMessage"?: string;
    }
    interface StencilKitButton {
        "buttonTitle"?: string;
    }
    interface StencilKitDiv {
    }
    interface StencilKitLink {
        "href"?: string;
        "linkTitle"?: string;
    }
    interface IntrinsicElements {
        "child-component": ChildComponent;
        "component-with-event": ComponentWithEvent;
        "my-component": MyComponent;
        "parent-component": ParentComponent;
        "stencil-kit-button": StencilKitButton;
        "stencil-kit-div": StencilKitDiv;
        "stencil-kit-link": StencilKitLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "child-component": LocalJSX.ChildComponent & JSXBase.HTMLAttributes<HTMLChildComponentElement>;
            "component-with-event": LocalJSX.ComponentWithEvent & JSXBase.HTMLAttributes<HTMLComponentWithEventElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "parent-component": LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
            "stencil-kit-button": LocalJSX.StencilKitButton & JSXBase.HTMLAttributes<HTMLStencilKitButtonElement>;
            "stencil-kit-div": LocalJSX.StencilKitDiv & JSXBase.HTMLAttributes<HTMLStencilKitDivElement>;
            "stencil-kit-link": LocalJSX.StencilKitLink & JSXBase.HTMLAttributes<HTMLStencilKitLinkElement>;
        }
    }
}
